FORMAT: 1A
HOST: https://api.previo.cz/app

# API - Housekeeping app API

## Allowed HTTPs requests:
- `GET` - Get a resource or list of resources
- `POST` - To create resource
- `PUT` - Update resource
- `DELETE` - To delete resource

## Common status codes:
- `200` - success
- `204` - success on DELETE (no content)
- `400` – something's wrong with request (check error message and display to user)
- `401` - missing or invalid authentication
- `5XX` – there's something wrong with server.

## Errors

Test Every response could return an error. When this happens status code is `4XX` or `5XX` and response body contains JSON formatted response like this:

```
{
    error: Failed to get data (string,required)
}
```

##Headers
```
X-Previo-Language-ID: {lanId} (In which language the application is running)
X-Previo-App-ID: 2
X-Previo-Hotel-ID: {hotId}
```

## Notification - OneSignal
 - On login
   - Set tag `userId = 7321`
 - On logout
   - Remove tag `userId`

### OneSignal data
 ```
 {
   type: 1,
   action: 1,
 }
 ```
 - `type`
  - `1` - Silent notification (refresh data in background)
  - `2` - Notification
  
 - `action` (the data specification that contains the data object)

## User info [/user]

### Get user info [GET /user{?versionCode}{?os}]

+ Parameters
    + versionCode: 1111 (number, required) - Version code of application build
    + os: android (string, required) - Type of operating system (ios, android)

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690
    
+ Response 200 (application/json)
    + Attributes (UserInfo)

### Save new notification setting [PUT /user/notification]

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690

    + Attributes (Notification)
    
+ Response 200 (application/json)

## Premises [/premise]

### Get premises list [GET /premise]
- Return all assigned premises for user, it user has no premises assigned it will return all premises at hotel with obtId = 1 (room).

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690
    
+ Response 200 (application/json)
    + Attributes (array[Premise])

### Get premise [GET /premise{?objId}]

+ Parameters
    + objId: 2342 (number, required) - The unique identifier of the premise

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690
    
+ Response 200 (application/json)
    + Attributes (Premise)

### Set premise clean status [PUT /premise/status{?objId}{?ocsId}]

+ Parameters
    + objId: 2342 (number, required) - The unique identifier of the premise
    + ocsId: 1 (number, required) - The unique identifier of status for premise (1 - untidy, 2 - tidy, 3 - inspection)
    
+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690

+ Response 200 (application/json)
    + Attributes (Premise)

## Fault on premises [/fault]

### Get fault list [GET /fault{?objId}]
- Return fault order by created, but resolved defects only with the old resolved two days.

+ Parameters
    + objId: 654567 (number,required) - The unique identifier for premise

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690
    
+ Response 200 (application/json)
    + Attributes (array[Fault])

### Add new fault [POST /fault{?objId}]

+ Parameters
    + objId: 654567 (number,required) - The unique identifier for premise

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690

    + Attributes (FaultAdd)
    
+ Response 200 (application/json)
    + Attributes (Fault)

### Set premise fault status [PUT /fault/status{?fauId}{?fasId}]

+ Parameters
    + fauId: 23412 (number, required) - The unique identifier of fault
    + fasId: 1 (number, required) - Fault status (1-fixed, 2-not fixed, 3-beeing repaired)

+ Response 200 (application/json)

### Delete fault [DELETE /fault{?fauId}]

+ Parameters
    + fauId: 654567 (number,required) - The unique identifier for fault

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690
    
+ Response 200 (application/json)

## List of hotels [/hotel]

### Get hotel list [GET /hotel]

`In development`

+ Request (application/json)
    + Headers
    
            X-Previo-Language-ID: 1
            X-Previo-App-ID: 2
            X-Previo-Hotel-ID: 14690
    
+ Response 200 (application/json)
    + Attributes (array[Hotel])

## System [/system]

### Code books [GET /system/codeBook]

`In development`
            
+ Response 200 (application/json)
    + Attributes (CodeBook)


## Data Structure

## UserInfo
+ useId: 2313 (number, required) - The unique identifier of the user
+ name: Marek Novák (string, required) - Username login of user
+ lanId: 1 (number, required) - The unique identifier for language, which user has set in Previo
+ paysApp: true (boolean, required) - If hotel pay for Housekeeping module - DEPRECATED
+ versionSupported: true (boolean, required) - Is application version supported
+ newerVersion: true (boolean, required) - Is newer aplication version
+ notificationSetting (Notification, required) - Setting of notification
+ permission (Permission, required) - Listed permissions for users

## Permission 
+ modules (ModulePermission, required) - Permission to view the module
+ privileges (Privileges, required) - Permission for each operations

## ModulePermission
+ cleaning: true (boolean, required) - Permission for view into cleaning module
+ faults: true (boolean, required) - Permission for view into fault module
+ minibar: true (boolean, required) - Permission for view into minibar module
+ lossesAndFinds: true (boolean, required) - Permission for view into lost and find module

## Privileges
+ services (ServicePermission, required) - Perrmission in service module

## ServicePermission
+ faultsAdd: true (boolean, required) - Permission for adding new fault
+ faultsEdit: true (boolean, required) - Permission for edit fault
+ faultsRemove: true (boolean, required) - Permission for remove fault
+ roomCleanlinessEdit: true (boolean, required) - Permission for change room state (untidy, tidy, inspection)

## Premise
+ objId: 2342 (number, required) - The unique identifier of the premise
+ name: Deluxe 101 (string, required) - Name of the premise
+ isOnGoing: true (boolean, required) - There is a reservation overlapping whole day
+ isCheckOut: true (boolean, required) - There is a reservation ending today and guests allready checked out
+ isCheckIn: false (boolean, required) - There is a reservation starting today and guests allready checked in
+ checkOut: `2017-01-01T00:00:00` (string, optional) - Date of todays check-out (ISO 8601)
+ checkIn: `2017-01-01T00:00:00` (string, optional) - Date of todays check-in (ISO 8601)
+ term (Term, optional) - Term of ongoing reservation, if there are two reservations today. Or term of first reservation in the future, max 8days in future
+ ocsId: 1 (number, required) - The unique identifier for premise state (1 - untidy, 2 - tidy, 3 - inspection) 
+ numOfFaults: 2 (number, required) - Returns count of fault on premise at state not fixed and beeing repaired
+ guestName: Inženýrka Tejfarová (string, optional) - If there is ongoing reservation, guestName will be the first guest of this reservation with name, otherwise this will be name of guest of the first reservation in the future, max 8days in future)
+ guestCount: 4 (number, optional) - Number of guests (If there is ongoing reservation, this will be guest cout of this reservation, otherwise this will be guest count of the first reservation in the future, max 8days in future) 
+ note: Vyzdobit pokoj růžemi (string, optional) - Reservation note

## Notification
+ guestDeparture: true (boolean, required) - Guest departure notification
+ newTodayReservation: true (boolean, required) - New reservation for today
+ newDefect: true (boolean, required) - New defect notification

##FaultAdd
+ fauId: 23412 (number, optional) - The unique identifier of fault
+ fatId: 1 (number, required) - Type od fault (1 - shower, 2 - TV, 3 - door lock, 4 - heating, 5 - light, 6 - other)
+ fasId: 1 (number, required) - Fault status (1-fixed, 2-not fixed, 3-beeing repaired)
+ description: Nejde zapnout televize, zase hosti ukradli baterie... (string, optional) - Description of fault
+ photo: `data:image/gif;base64,R0lGODlhPQBEAP...` (string, optional) - Photo decoded in base64 (deprecated)
+ photos: `data:image/gif;base64_R0lGODlhPQBEAP...`, `data:image/gif;base64_R0lGODlhPQBEAP...` (array, required) - Array of photos URL
+ created: `2017-01-01T00:00:00Z` (string, required) - Date of created fault (ISO 8601)

##Fault
+ fauId: 23412 (number, required) - The unique identifier of fault
+ fatId: 1 (number, required) - Type od fault (1 - shower, 2 - TV, 3 - door lock, 4 - heating, 5 - light, 6 - other)
+ fasId: 1 (number, required) - Fault status (1-fixed, 2-not fixed, 3-beeing repaired)
+ description: Nejde zapnout televize, zase hosti ukradli baterie... (string, optional) - Description of fault
+ photo: `https://www.previo.cz/images/logo/logo-previo-@2x.png` (string, optional) - Photo url (deprecated)
+ photos: `https://www.previo.cz/images/logo/logo-previo-@2x.png`, `https://www.previo.cz/images/logo/logo-previo-@2x.png` (array, required) - Array of photos URL
+ created: `2017-01-01T00:00:00Z` (string, required) - Date of created fault (ISO 8601)

## Hotel 
+ hotId: 2342 (number, required) - The unique identifier of the hotel
+ name: Kubínos (string, required) - Name of the hotel

## CodeBook
+ premisesStates (array[PremisesState])
+ faultStates (array[FaultState])
+ faultTypes (array[FaultType])

## Term
+ from: `2017-01-01T00:00:00` (string, optional) - (ISO 8601)
+ to: `2017-01-05T14:00:00` (string, optional) - (ISO 8601)

## PremisesState
+ ocsId: 1 (number, required) - The unique identifier for premise state
+ name: untidy (string, required) - Name of premises state

## FaultState
+ fasId: 1 (number, required) -  The unique identifier for fault state
+ name: fixed (string, required) - Name of fault state

## FaultType
+ fatId: 1 (number, required) - The unique identifier for fault type
+ name: shower (string, required) - Name of fault type
